service: contacts-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: go1.x
  region: us-east-1

plugins:
  - serverless-offline

package:
  individually: true
  exclude:
    - ./**
  include:
    - ./bin/**

custom:
  serverless-offline:
    noPrependStageInUrl: true

functions:
  api:
    handler: bin/api
    events:
      - http:
          path: "{proxy+}"
          method: any
