service: contacts-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: go1.x
  region: us-east-1

plugins:
  - serverless-dynamodb-local
  - serverless-offline

package:
  individually: true
  exclude:
    - ./**
  include:
    - ./bin/**

custom:
  serverless-offline:
    noPrependStageInUrl: true
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

functions:
  health:
    handler: bin/health
    events:
      - http:
          path: /health
          method: GET
